#!/usr/bin/perl -w

#
# Copyright (c) 2008 Rainer Clasen
#
# This program is free software; you can redistribute it and/or modify
# it under the terms described in the file LICENSE included in this
# distribution.
#

=pod

=head1 NAME

Dudl::Overview - the Dudl music framework Overview

=head1 DESCRIPTION

The Dudl music framework is a set of tools / SQL Tables that are intended
to cover the whole life of MP3: From ripping the CD over encoding and
renaming to archiving and playback.

As this is a quite broad area of interest, the framework is split into the
below mentioned components. Usually tools for such a component are named
dudl-<component>blah.

On their way to the DB MP3s are acompanied by so called jobfiles. These
jobfiles are used to record meta information, that might get used for the
next step.

=over 4

=item B<grab>

Grab raw data from a CD, get titlenames from FreeDB and generate a jobfile
for later processing.

=item B<encode>

Encode the grabbed raw data to MP3. There are also tools to distribute
encoding accross several CPUs. If there is demand, encoding might also be
extended to utilize several hosts. Enoding takes a jobfile as generated by
dudl-grab and generates one apropriate for renaming.

=item B<ren> (rename)

Renames encoded MP3s in a consistent manner and sets their ID3 Tags. If
you don't have a jobfile supplied from I<dudl-encode>(1), you can use
I<dudl-rengen>(1) to generate one. The later one looks at the filename and
ID3 Tags to guess the correct information (artist, album, title, ...)

=item B<do> (process new stuff)

To keep track of grab, encode, rename and test-listening there are a few
tools to ease this task. There are helpers to move the files around or
execute other repetetive tasks. These tools are not yet configurable and
rely on a hard-coded directory structure with the subdirectories 0grab
1encode 2test 3ren/<genre> 4out/<genre> 5done.

=cut

# TODO: include /pub/fun/mp3/README.txt

=pod

=item B<archive>

Files are expected to reside in
<cdpath>/<collection>/<collection><colnum>/<dir(s)>/<fname>

<cdpath> is the top archive directory as set in your config. It should've
been named unitpath ;-)

<colnum> is the 4-digit unit number (with leading zeros).

Other parts of the documentation refer to the "<collection><colnum>"
combination as <unit> or <unitname>.

And remember: You're free to use symlinks to map your physical data to
this layout.

Please take a look at I<Dudl::DBOverview>(3) for some terms used above.

=item B<db> (Database)

split into several components:

=over 4

=item B<stor> (storage - DB view of archive)

=item B<mus> (music)

=item B<juke> (jukebox - DB infrastructure for dudld)

=back

Please take a look at I<Dudl::DBOverview>(3) for details.

=item B<dudl-www>

some quick'n'dirty CGI scripts to browse the Dudl Database.

=item B<dudld>

The jukebox daemon. It is designed to run just ontop of the music
database and therefore lacks thorough editing capabilities for the DB.

=item B<dudlc>

The jukebox clients. There is a client library that's used by both
clients I<dudlc>(1) and I<irdudl>(1).

=back

=head1 SEE ALSO

I<Dudul::DBOverview>

=head1 AUTHOR

Rainer Clasen

=cut
