#! /usr/bin/perl -w

# $Id: dudl-dotest,v 1.5 2006-01-27 13:06:19 bj Exp $

use strict;
use Getopt::Long;
use Dudl::Config;
use Dudl::Misc;

=pod

=head1 NAME

dudl-dotest - add MP3 directory to testing workspace

=head1 SYNOPSIS

dudl-dotest [<opts>] <dir> ...

=head1 DESCRIPTION

TODO: man desc


=head1 OPTIONS

=over 4

=item B<--prefix>=<string>

prefix new directory names with speciefied string.

=cut

my $opt_prefix = "";

=item B<--help>

display short usage info.

=cut

my $wanthelp;
my $needhelp;

if( ! GetOptions(
	"help!"		=> \$wanthelp,
	"prefix=s"	=> \$opt_prefix,
)){
	$needhelp++;
}

if( $#ARGV < 0 ){
	print STDERR "missing directory\n";
	$needhelp++;
}


if( $wanthelp ){
	print <<EOF;
usage: $0 <opts> <dir> ...
 add MP3 directory to testing workspace
options:
 --help                  this short usage information.
 --prefix <string>       prefix new directory names with speciefied string
EOF
	exit 0;
}

if( $needhelp ){
	print STDERR "use --help for usage info\n";
	exit 1;
}

my $dudl = new Dudl::Config;
my $nam = $dudl->naming;
my $tdir = $dudl->conf("workpath"). "/2test";

if( $opt_prefix && $opt_prefix !~ /-$/ ){
	$opt_prefix .= "-";
}

foreach my $src ( @ARGV ){
	unless( -d $src ){
		print STDERR "skipping non-dir: $src\n";
		next;
	}

	if( &samedir( &parentdir( $src ), $tdir )){
		print STDERR "already in testing workspace: $src\n";
		next;
	}

	$src =~ /([^\/]+)\/*$/;
	my $dst = $tdir . "/". $nam->fnormalize( $opt_prefix.$1 );
	system( "mv \"$src\" \"$dst\"" ) == 0
		or die "mv failed: $1";

	-e "$dst/ren" || &mkren( $dst )
		or die "creating jobfile failed";
}

sub mkren {
	my( $dst ) = @_;

	# TODO: re-user M3U playlists

	# TODO: perlify jobfile generation
	system( "cd \"$dst\" && find . -type f -iname \\*.mp3 | sort | ( printf \"TODO: edit\\n# TODO: year\\n\"; dudl-rengen - ) > ren 2>/dev/null") == 0
		or return;

	return 1;
}

=pod

=head1 EXAMPLES

dudl-dotest --prefix metallica- master.of.puppets/

=head1 SEE ALSO

I<Dudl::Overview>

=head1 AUTHOR

Rainer Clasen

=cut



