#!/bin/sh

# move dirs from 2test 
# - to 4ren using dudl-rename if "ren" file works flawlessly
# - to 3ren otherwise

# dudl-doren <genre> <dir1> [...]

set -e
rdir="/pub/fun/mp3/3ren"
odir="/pub/fun/mp3/4out"

genre="`echo "$1" | tr '[a-z]' '[A-Z]' `"
shift

case "$genre" in
 COMEDY|DANCE|POP|ROCK|SAMPLER)
	:
	;;
 *)
 	echo "invalid genre: >$genre<"
	exit 1
	;;
esac


for i in "$@"; do
	if [ -d "$i" ]; then
		sdir="$i"
		ren="$sdir/ren"
	else
		ren="$i"
		sdir="${i%/*}"
	fi

	echo "processing $ren"
	if dudl-rename --test "$ren" > /dev/null 2>&1 ; then
		gdir="$odir/$genre"
		[ -d "$gdir" ] || mkdir "$gdir"

		dudl-rename --outdir="$gdir" "$ren"
		echo "hit ^C on error, ENTER on success"
		read
		rm -rf "$sdir"
	else
		gdir="$rdir/$genre"
		[ -d "$gdir" ] || mkdir "$gdir"

		# TODO: avoid overwriting itself
		mv "$sdir" "$gdir/"
	fi
done
# TODO: GetOptions + usage or perlify
# TODO: manpage
