#!/usr/bin/perl -w

# show some statistics

# $Id: dudl-dbstatus,v 1.2 2006-01-13 15:41:23 bj Exp $

use strict;
use Dudl::DB;

my $dudl = new Dudl::DB;
my $db = $dudl->db;

# TODO: move database access to module

&col( "units",		"SELECT COUNT(*),0 FROM stor_unit");
&col( "sl units",	"SELECT max(colnum),0 FROM stor_unit WHERE collection='sl'");
&col( "files all",	"SELECT COUNT(*),SUM(fsize)/1073741824 FROM stor_file");
&col( "files intact",	"SELECT COUNT(*),SUM(fsize)/1073741824 FROM stor_file WHERE NOT broken");
&col( "albums",		"SELECT COUNT(*),0 FROM mus_album");
&col( "titles all",	"SELECT COUNT(*),SUM(fsize)/1073741824 FROM stor_file WHERE album_id NOTNULL");
&col( "titles nontmp",	"SELECT COUNT(*),SUM(fsize)/1073741824 FROM stor_file WHERE album_id > 0");

sub col {
	my( $desc, $query ) = @_;
	my( $num, $sz ) = $db->selectrow_array( $query );
	printf "%-15s %15d %15d\n", $desc, $num, $sz;
}

=pod
	"SELECT ".
		"trim(collection), ".
		"colnum, ".
		"dir, ".
		"COUNT(title) as titles, ".
		"COUNT(dir) as files ".
	"FROM ".
		"stor_file f, ".
		"stor_unit u ".
	"WHERE ".
		"f.unit_id = u.id ".
	"GROUP BY ".
		"dir ".
	"ORDER BY ".
		"collection, ".
		"colnum, ".
		"dir ";
=cut




