#!/usr/bin/perl -w

# $Id: dudl-stordupes,v 1.4 2006-01-27 13:06:19 bj Exp $

# TODO: move database access to module

use strict;
use Dudl::DB;
use Getopt::Long;

my $wanthelp;
my $needhelpt;

if( ! GetOptions(
	"help|h!"	=> \$wanthelp,
)){
	$needhelp++;
}

if( $wanthelp ){
	print <<EOF;
usage: $0 <opt>
 find duplicate files using their stored md5sums
options:
 --help                  this short usage information.
EOF
	exit 0;
}

if( $needhelp ){
	print STDERR "use --help for usage info\n";
	exit 1;
}


=pod

=head1 NAME

dudl-stordupes - find duplicate files using their stored md5sums

=head1 SYNOPSIS

dudl-stordupes

=head1 DESCRIPTION

finds duplicate files by their stored md5sums

=head1 SEE ALSO

I<Dudl::Overview>

=head1 AUTHOR

Rainer Clasen

=cut

my $dudl = new Dudl::DB;

sub run {
	my $db		= shift;
	my $field	= shift;

	my $query;
	my $sth;
	my $res;

	$query =
		"SELECT $field ".
		"INTO TEMP tmp_$field ".
		"FROM stor_file ".
		"GROUP BY $field ".
		"HAVING count(*) > 1";
	$res = $db->do( $query );
	if( ! $res ){
		die $db->errstr ."\nquery: $query\n";
	}

	$query =
		"SELECT ".
			"tmp_$field.$field, ".
			"trim(collection), ".
			"colnum, ".
			"dir, ".
			"fname ".

		"FROM ".
			"tmp_$field, ".
			"stor_file, ".
			"stor_unit ".
		"WHERE ".
			"(tmp_$field.$field = stor_file.$field) AND ".
			"(stor_file.unit_id = stor_unit.id ) ".
		"ORDER BY ".
			"tmp_$field.$field";
	$sth = $db->prepare( $query );
	if( ! $sth ){
		die $db->errstr ."\nquery: $query\n";
	}

	$res = $sth->execute;
	if( ! $res ){
		die $sth->errstr ."\nquery: $query\n";
	}

	my( $sum, $collection, $colnum, $dir, $fname );
	$sth->bind_columns( \( $sum, $collection, $colnum, $dir, $fname ) );

	my $osum;
	while( defined $sth->fetch ){
		if( $osum ne $sum ){
			print "\n";
			$osum = $sum;
		}
		print join("/", $collection.$colnum, $dir, $fname), "\n";
	}
}

print "\nduplicates by file:\n";
&run( $dudl->db, "fsum" );

print "\nduplicates by data:\n";
&run( $dudl->db, "dsum" );

