#!/usr/bin/perl -w

# $Id: dudl-musdirs,v 1.1 2006-01-11 13:50:36 bj Exp $

# list directories of a unit

# show number of files
# show if all/some files in directory have links in mus_

use strict;
use Dudl::DB;
use Dudl::StorUnit;

my $dudl = new Dudl::DB;
my $db = $dudl->db;

my $unitname = shift || die "need a unit name";

my $unit = Dudl::StorUnit->load_path( dudl => $dudl, path => $unitname );
if( ! $unit ){
	print STDERR "no such unit found: $unitname\n";
	exit 1;
}
my $id = $unit->val("id");

# TODO: move database access to module
my $query = 
	"SELECT ".
		"dir, ".
		"COUNT(title) as titles, ".
		"COUNT(dir) as files ".
	"FROM stor_file ".
	"WHERE ".
		"unit_id = $id ".
		" AND NOT broken ".
	"GROUP BY ".
		"dir ".
	"ORDER BY ".
		"dir ";

my $sth = $db->prepare( $query );
if( ! $sth ){
	die $db->errstr ."\nquery: $query\n";
}

my $res = $sth->execute;
if( ! $res ){
	die $sth->errstr ."\nquery: $query\n";
}

my( $dir, $titles, $files );
$sth->bind_columns( \( $dir, $titles, $files ) );

printf "%4s %4s %7s %s\n", "tit", "fil", "unit", "dir";
while( defined $sth->fetch ){
	printf "%4s %4d %7d %s\n", $titles, $files, $id, $dir;
}	
$sth->finish;


