#!/bin/sh

# try to move dirs from 3ren to 4out using dudl-rename
#  dudl-doout <genre> <dir1> ...
#  dudl-doout   # automagically picks all from 3ren


set -e

rdir="/pub/fun/mp3/3ren"
odir="/pub/fun/mp3/4out"

do_genre() {
	local genre="$1"
	shift

	case "$genre" in
	 COMEDY|DANCE|POP|ROCK|SAMPLER)
		:
		;;
	 *)
		echo "invalid genre: >$genre<"
		exit 1
		;;
	esac

	gdir="$odir/$genre"
	[ -d "$gdir" ] || mkdir "$gdir"

	for i in "$@"; do
		if [ "$i"x = "*/"x ]; then
			break
		fi

		if [ -d "$i" ]; then
			sdir="$i"
			ren="$sdir/ren"
		else
			ren="$i"
			sdir="${i%/*}"
		fi

		dudl-rename --outdir="$gdir" $ren
		echo "hit ^C on error, ENTER on success"
		read
		rm -rf "$sdir"
	done
}

if [ $# -eq 0 ]; then
	cd "$rdir"
	for sdir in */; do
		( 
		cd "$sdir"
		genre=${sdir%%/}
		do_genre "$genre" */
		) || exit 1
	done
else
	genre="`echo "$1" | tr '[a-z]' '[A-Z]' `"
	shift

	do_genre "$genre" "$@"
fi
# TODO: GetOptions + usage or perlify
# TODO: manpage
