#!/usr/bin/perl -w

# $Id: dudl-dbstatus,v 1.3 2006-01-25 16:37:28 bj Exp $

use strict;
use Dudl::DB;

=pod

=head1 NAME

dudl-dbstatus - show some Database statistics

=head1 DESCRIPTION

This script shows some statistics for the Dudl Database. The output is
split into 3 columns:

=over 4

=item 1

Description.

=item 2

Number.

=item 3

Size in GigaByte.

=back

=head1 SEE ALSO

I<Dudl::Overview>

=head1 AUTHOR

Rainer Clasen

=cut

my $dudl = new Dudl::DB;
my $db = $dudl->db;

# TODO: move database access to module

&col( "units",		"SELECT COUNT(*),0 FROM stor_unit");
&col( "sl units",	"SELECT max(colnum),0 FROM stor_unit WHERE collection='sl'");
&col( "files all",	"SELECT COUNT(*),SUM(fsize)/1073741824 FROM stor_file");
&col( "files intact",	"SELECT COUNT(*),SUM(fsize)/1073741824 FROM stor_file WHERE NOT broken");
&col( "albums",		"SELECT COUNT(*),0 FROM mus_album");
&col( "titles all",	"SELECT COUNT(*),SUM(fsize)/1073741824 FROM stor_file WHERE album_id NOTNULL");
&col( "titles nontmp",	"SELECT COUNT(*),SUM(fsize)/1073741824 FROM stor_file WHERE album_id > 0");

sub col {
	my( $desc, $query ) = @_;
	my( $num, $sz ) = $db->selectrow_array( $query );
	printf "%-15s %15d %15d\n", $desc, $num, $sz;
}

=pod
	"SELECT ".
		"trim(collection), ".
		"colnum, ".
		"dir, ".
		"COUNT(title) as titles, ".
		"COUNT(dir) as files ".
	"FROM ".
		"stor_file f, ".
		"stor_unit u ".
	"WHERE ".
		"f.unit_id = u.id ".
	"GROUP BY ".
		"dir ".
	"ORDER BY ".
		"collection, ".
		"colnum, ".
		"dir ";
=cut




# TODO: GetOptions + usage
