#!/usr/bin/perl -w

# $Id: dudl-dbmaintenance,v 1.7 2007-03-21 10:20:14 bj Exp $

use strict;
use Dudl::DB;
use Getopt::Long;

my $wanthelp;
my $needhelp;

if( ! GetOptions(
	"help|h!"	=> \$wanthelp,
)){
	$needhelp++;
}

if( $wanthelp ){
	print <<EOF;
usage: $0 <opt>
 periodic database maintenance
options:
 --help                  this short usage information.
EOF
	exit 0;
}

if( $needhelp ){
	print STDERR "use --help for usage info\n";
	exit 1;
}


=pod

=head1 NAME

dudl-dbmaintenance - periodic database maintenance

=head1 DESCRIPTION

This script takes care of cleaning the dudl Database. Namely it does


=over 4

=cut

my $dudl = new Dudl::DB;
my $db = $dudl->db;

=pod

=item *

purge old jukebox history entries.

=cut
$db->do( 
"DELETE FROM mserv_hist ".
"WHERE ".
	"age(added) > interval '6 month' ".
	"AND NOT last" )
	or die $db->errstr;
$db->commit;

# TODO: remove albums + titles when all titles are broken

=pod

=item *

delete albums without titles (except UNSORTED)

=cut

$db->do(
"DELETE FROM mus_album ".
"WHERE id IN ( ".
	"SELECT a.id ".
	"FROM mus_album a ".
		"LEFT JOIN stor_file f ON a.id = f.album_id ".
	"WHERE a.album != 'UNSORTED' ".
	"GROUP BY a.id ".
	"HAVING COUNT(f.id) = 0)")

	or die $db->errstr;
$db->commit;

=pod

=item *

delete artists without titles/albums (except UNKNOWN, VARIOUS)

=cut

$db->do(
"DELETE FROM mus_artist ".
"WHERE id IN ( ".
	"SELECT ar.id ".
	"FROM mus_artist ar ".
		"LEFT JOIN (SELECT f.artist_id ".
			"FROM stor_file f ".
		"UNION ALL SELECT al.artist_id ".
			"FROM mus_album al) ids ON ar.id = ids.artist_id ".
	"WHERE NOT ar.nname IN( 'UNKNOWN', 'VARIOUS' ) ".
	"GROUP BY ar.id ".
	"HAVING COUNT(ids.artist_id) = 0)")

	or die $db->errstr;
$db->commit;

# vacuum analyze
#$db->{AutoCommit} = 1;
#$sth = $db->do( "VACUUM ANALYZE" )
#	or die $db->errstr;


=pod

=back

It is recommended to run this script from a daily cron job.

=head1 SEE ALSO

I<Dudl::Overview>

=head1 AUTHOR

Rainer Clasen

=cut

