#!/bin/sh

# move new album to test directory normalizing all filenames
#  dudl-dotest <dir> ...
#  prefix=metallica- dudl-dotest master.of.puppets

set -e

: ${prefix:=}
tstdir=/pub/fun/mp3/2test

do_dir () {
	local src="$1"
	if [ -d "$src" ]; then : ; else
		echo "skipping non-dir: $src" >&2
		return 1
	fi

	# TODO: strip trailing 'the|die|...' from directory names
	dst="$(dudl-fname "`basename "$src"`")"
	mv "$src" "$tstdir/$prefix$dst"
	(
		cd "$tstdir/$prefix$dst" 
		dudl-fclean *
		[ -r ren ] \
			|| find . -type f -iname \*.mp3 \
			| sort \
			| ( 
				printf "TODO: edit\n# TODO: year\n"
				dudl-rengen -
			)  > ren 2>/dev/null 
	)
}

if [ $# -gt 0 ]; then
	for src in "$@"; do
		do_dir "$src"
	done
else
	while read src; do
		do_dir "$src"
	done
fi

